# Generated by Django 6.0.6 on 2026-06-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
